In [1]:
import pandas as pd
df = pd.read_csv("only_normalized_data.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   name_p_BRI                  76 non-null     bool
 1   name_p_BRIS                 76 non-null     bool
 2   name_p_COB TUBE             76 non-null     bool
 3   name_p_COSTA                76 non-null     bool
 4   name_p_Cob magnet           76 non-null     bool
 5   name_p_Deep SMD             76 non-null     bool
 6   name_p_JIMI                 76 non-null     bool
 7   name_p_MINI B               76 non-null     bool
 8   name_p_MINI C               76 non-null     bool
 9   name_p_PATENT               76 non-null     bool
 10  name_p_SELINE               76 non-null     bool
 11  name_p_STEPS                76 non-null     bool
 12  name_p_TORRES               76 non-null     bool
 13  color_p_B                   76 non-null     bool
 14  color_p_G                   76 non-null     bool
 15  color_p_W                   76 non-null     bool
 16  color_p_WG                  76 non-null     bool
 17  color_p_b                   76 non-null     bool
 18  color_p_g                   76 non-null     bool
 19  color_p_w                   76 non-null     bool
 20  Inventory value_normalized  76 non-null     float64
 21  Inventory_normalized        76 non-null     float64
 22  Total orders_normalized     76 non-null     float64
 23  total 23_normalized         76 non-null     float64
 24  January_normalized          76 non-null     float64
 25  February_normalized         76 non-null     float64
 26  March_normalized            76 non-null     float64
 27  April_normalized            76 non-null     float64
 28  May_normalized              76 non-null     float64
 29  June_normalized             76 non-null     float64
 30  July_normalized             76 non-null     float64
 31  August_normalized           76 non-null     float64
 32  September_normalized        76 non-null     float64
 33  October_normalized          76 non-null     float64
 34  Novermber_normalized        76 non-null     float64
 35  December_normalized         76 non-null     float64
 36  AV23_normalized             76 non-null     float64
 37  multiplier_normalized       76 non-null     float64
 38  Minimum stock_normalized    76 non-null     float64
 39  purchase_r_normalized       76 non-null     float64
dtypes: bool(20), float64(20)
memory usage: 13.5 KB

In [3]:
rest_columns = df[['name_p_BRI', 'name_p_BRIS', 'name_p_COB TUBE','name_p_COSTA','name_p_Cob magnet','name_p_Deep SMD','name_p_JIMI','name_p_MINI B','name_p_MINI C','name_p_PATENT','name_p_SELINE','name_p_STEPS','name_p_TORRES','color_p_B','color_p_G','color_p_W','color_p_WG','color_p_b','color_p_g','color_p_w','Inventory value_normalized','Inventory_normalized','Total orders_normalized','total 23_normalized','AV23_normalized','multiplier_normalized','Minimum stock_normalized','purchase_r_normalized']]

In [13]:
month_columns = [col for col in df.columns if col.endswith('_normalized')]
months_df = pd.melt(df, value_vars=month_columns, var_name='Month', value_name='Value')
months_df['Month'] = months_df['Month'].str.split('_').str[0]

month_dict = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'Novermber': 11, 'December': 12
}
months_df['Month'] = months_df['Month'].map(month_dict)

In [14]:
months_df.reset_index(inplace=True)
months_df.rename(columns={'index': 'code_p'}, inplace=True)

In [10]:
code_p_values = [
    15126, 15127, 15002, 150022, 150011, 15001, 150033, 15003, 15004, 15006,
    150044, 15005, 150055, 150066, 15306, 15303, 15304, 15307, 15305, 15308,
    15302, 15301, 15450, 15452, 15453, 15455, 15456, 15458, 15451, 15454,
    15457, 15084, 15087, 15080, 15081, 15086, 15083, 15088, 15085, 15082,
    15907, 15906, 15915, 15916, 15908, 15913, 15914, 15911, 15910, 15387,
    15909, 15386, 15912, 15917, 15027, 150277, 15028, 150288, 15007, 15008,
    150077, 150088, 150099, 15009, 15061, 15062, 15060, 150611, 150622,
    150600, 15037, 15039, 15040, 15038, 15041, 15394
]
df['code_p'] = code_p_values

In [63]:
df.set_index('code_p', inplace=True)

In [25]:
df.to_csv("final_dataset.csv", index=True)

In [61]:
df.drop(labels="level_0", axis=1,inplace=True)

In [18]:
rest_columns = df[['name_p_BRI', 'name_p_BRIS', 'name_p_COB TUBE','name_p_COSTA','name_p_Cob magnet','name_p_Deep SMD','name_p_JIMI','name_p_MINI B','name_p_MINI C','name_p_PATENT','name_p_SELINE','name_p_STEPS','name_p_TORRES','color_p_B','color_p_G','color_p_W','color_p_WG','color_p_b','color_p_g','color_p_w','Inventory value_normalized','Inventory_normalized','Total orders_normalized','total 23_normalized','AV23_normalized','multiplier_normalized','Minimum stock_normalized','purchase_r_normalized']]
combined_df = pd.concat([melted_df, rest_columns], axis=1)

In [60]:
df.drop(labels="index", axis=1,inplace=True)

In [64]:
df

,name_p_BRI,name_p_BRIS,name_p_COB TUBE,name_p_COSTA,name_p_Cob magnet,name_p_Deep SMD,name_p_JIMI,name_p_MINI B,name_p_MINI C,name_p_PATENT,name_p_SELINE,name_p_STEPS,name_p_TORRES,color_p_B,color_p_G,color_p_W,color_p_WG,color_p_b,color_p_g,color_p_w
code_p,,,,,,,,,,,,,,,,,,,,
15126,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
15127,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False
15002,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
150022,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
150011,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15039,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False
15040,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
15038,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False
15041,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
15394,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False